default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: stache_yo_self_development

test:
  <<: *default
  database: stache_yo_self_test

production:
  <<: *default
  database: stache_yo_self_production
  password: <%= ENV['STACHE_YO_SELF_DATABASE_PASSWORD'] %>
